robot:
  - name: "square"
    joint: "flying"
    limits:
      upper: [ 20,  20]
      lower: [-20, -20]
    geometry:
      - type: "box"
        dimensions: [0.5, 0.5]

  - name: "obstacle_1"
    joint: "fixed"
    geometry: 
      - type: "box"
        dimensions: [3.5, 1]
        offset: [-4, 6, 0]
        color: [0.5, 0.3, 0.2, 1]

  - name: "obstacle_2"
    joint: "fixed"
    geometry: 
      - type: "box"
        dimensions: [3.5, 1]
        offset: [-4, -6, 0]
        color: [0.5, 0.3, 0.2, 1]

  - name: "obstacle_3"
    joint: "fixed"
    geometry: 
      - type: "box"
        dimensions: [1, 5]
        offset: [-1.5, 0, 0]
        color: [0.5, 0.3, 0.2, 1]


  - name: "obstacle_4"
    joint: "fixed"
    geometry: 
      - type: "box"
        dimensions: [2.5, 1]
        offset: [3.5, 0, 0]
        color: [0.5, 0.3, 0.2, 1]

  - name: "obstacle_5"
    joint: "fixed"
    geometry: 
      - type: "box"
        dimensions: [1, 10]
        offset: [7, 0, 0]
        color: [0.5, 0.3, 0.2, 1]



states:
  - name: "start"
    configuration:
    - frame: "square"
      value: [-8, 8, 0]

  - name: "goal"
    configuration:
    - frame: "square"
      value: [1,1, 1]
